//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllLifePricingWeb.AllLifeGeneric {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/AllLifeGeneric")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDValidationResult", Namespace="http://schemas.datacontract.org/2004/07/AllLifeGeneric.Classes")]
    [System.SerializableAttribute()]
    public partial class IDValidationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizenship {
            get {
                return this.CitizenshipField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipField, value) != true)) {
                    this.CitizenshipField = value;
                    this.RaisePropertyChanged("Citizenship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AllLifeGeneric.IAllLifeGeneric")]
    public interface IAllLifeGeneric {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/GetData", ReplyAction="http://tempuri.org/IAllLifeGeneric/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/GetData", ReplyAction="http://tempuri.org/IAllLifeGeneric/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAllLifeGeneric/GetDataUsingDataContractResponse")]
        AllLifePricingWeb.AllLifeGeneric.CompositeType GetDataUsingDataContract(AllLifePricingWeb.AllLifeGeneric.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAllLifeGeneric/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.AllLifeGeneric.CompositeType> GetDataUsingDataContractAsync(AllLifePricingWeb.AllLifeGeneric.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/IDValidation", ReplyAction="http://tempuri.org/IAllLifeGeneric/IDValidationResponse")]
        AllLifePricingWeb.AllLifeGeneric.IDValidationResult IDValidation(string IDNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifeGeneric/IDValidation", ReplyAction="http://tempuri.org/IAllLifeGeneric/IDValidationResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.AllLifeGeneric.IDValidationResult> IDValidationAsync(string IDNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllLifeGenericChannel : AllLifePricingWeb.AllLifeGeneric.IAllLifeGeneric, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllLifeGenericClient : System.ServiceModel.ClientBase<AllLifePricingWeb.AllLifeGeneric.IAllLifeGeneric>, AllLifePricingWeb.AllLifeGeneric.IAllLifeGeneric {
        
        public AllLifeGenericClient() {
        }
        
        public AllLifeGenericClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllLifeGenericClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllLifeGenericClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllLifeGenericClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AllLifePricingWeb.AllLifeGeneric.CompositeType GetDataUsingDataContract(AllLifePricingWeb.AllLifeGeneric.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.AllLifeGeneric.CompositeType> GetDataUsingDataContractAsync(AllLifePricingWeb.AllLifeGeneric.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public AllLifePricingWeb.AllLifeGeneric.IDValidationResult IDValidation(string IDNumber) {
            return base.Channel.IDValidation(IDNumber);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.AllLifeGeneric.IDValidationResult> IDValidationAsync(string IDNumber) {
            return base.Channel.IDValidationAsync(IDNumber);
        }
    }
}
