//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllLifePricingWeb.WS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.IAllLifePrincing")]
    public interface IAllLifePrincing {
        
        // CODEGEN: Parameter 'GetDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/GetData", ReplyAction="http://tempuri.org/IAllLifePrincing/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.GetDataResponse GetData(AllLifePricingWeb.WS.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/GetData", ReplyAction="http://tempuri.org/IAllLifePrincing/GetDataResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataResponse> GetDataAsync(AllLifePricingWeb.WS.GetDataRequest request);
        
        // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAllLifePrincing/GetDataUsingDataContractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.GetDataUsingDataContractResponse GetDataUsingDataContract(AllLifePricingWeb.WS.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAllLifePrincing/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(AllLifePricingWeb.WS.GetDataUsingDataContractRequest request);
        
        // CODEGEN: Parameter 'returnPremiumResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnPremium", ReplyAction="http://tempuri.org/IAllLifePrincing/returnPremiumResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnPremiumResponse returnPremium(AllLifePricingWeb.WS.returnPremiumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnPremium", ReplyAction="http://tempuri.org/IAllLifePrincing/returnPremiumResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnPremiumResponse> returnPremiumAsync(AllLifePricingWeb.WS.returnPremiumRequest request);
        
        // CODEGEN: Parameter 'returnRiskResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnRisk", ReplyAction="http://tempuri.org/IAllLifePrincing/returnRiskResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnRiskResponse returnRisk(AllLifePricingWeb.WS.returnRiskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnRisk", ReplyAction="http://tempuri.org/IAllLifePrincing/returnRiskResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskResponse> returnRiskAsync(AllLifePricingWeb.WS.returnRiskRequest request);
        
        // CODEGEN: Parameter 'returnCoverResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnCover", ReplyAction="http://tempuri.org/IAllLifePrincing/returnCoverResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnCoverResponse returnCover(AllLifePricingWeb.WS.returnCoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnCover", ReplyAction="http://tempuri.org/IAllLifePrincing/returnCoverResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnCoverResponse> returnCoverAsync(AllLifePricingWeb.WS.returnCoverRequest request);
        
        // CODEGEN: Parameter 'returnEM_Affected_PremiumResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Premium", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_PremiumResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse returnEM_Affected_Premium(AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Premium", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_PremiumResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse> returnEM_Affected_PremiumAsync(AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest request);
        
        // CODEGEN: Parameter 'returnEM_Affected_RiskResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Risk", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_RiskResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnEM_Affected_RiskResponse returnEM_Affected_Risk(AllLifePricingWeb.WS.returnEM_Affected_RiskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Risk", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_RiskResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_RiskResponse> returnEM_Affected_RiskAsync(AllLifePricingWeb.WS.returnEM_Affected_RiskRequest request);
        
        // CODEGEN: Parameter 'returnEM_Affected_CoverResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Cover", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_CoverResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnEM_Affected_CoverResponse returnEM_Affected_Cover(AllLifePricingWeb.WS.returnEM_Affected_CoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnEM_Affected_Cover", ReplyAction="http://tempuri.org/IAllLifePrincing/returnEM_Affected_CoverResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_CoverResponse> returnEM_Affected_CoverAsync(AllLifePricingWeb.WS.returnEM_Affected_CoverRequest request);
        
        // CODEGEN: Parameter 'returnRiskBandResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnRiskBand", ReplyAction="http://tempuri.org/IAllLifePrincing/returnRiskBandResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.returnRiskBandResponse returnRiskBand(AllLifePricingWeb.WS.returnRiskBandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/returnRiskBand", ReplyAction="http://tempuri.org/IAllLifePrincing/returnRiskBandResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskBandResponse> returnRiskBandAsync(AllLifePricingWeb.WS.returnRiskBandRequest request);
        
        // CODEGEN: Parameter 'QualifyLifeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/QualifyLife", ReplyAction="http://tempuri.org/IAllLifePrincing/QualifyLifeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.QualifyLifeResponse QualifyLife(AllLifePricingWeb.WS.QualifyLifeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/QualifyLife", ReplyAction="http://tempuri.org/IAllLifePrincing/QualifyLifeResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyLifeResponse> QualifyLifeAsync(AllLifePricingWeb.WS.QualifyLifeRequest request);
        
        // CODEGEN: Parameter 'QualifyDisabilityResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/QualifyDisability", ReplyAction="http://tempuri.org/IAllLifePrincing/QualifyDisabilityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AllLifePricingWeb.WS.QualifyDisabilityResponse QualifyDisability(AllLifePricingWeb.WS.QualifyDisabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllLifePrincing/QualifyDisability", ReplyAction="http://tempuri.org/IAllLifePrincing/QualifyDisabilityResponse")]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyDisabilityResponse> QualifyDisabilityAsync(AllLifePricingWeb.WS.QualifyDisabilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AllLifePricing")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
                this.RaisePropertyChanged("BoolValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
                this.RaisePropertyChanged("BoolValueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
                this.RaisePropertyChanged("StringValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AllLifePricingWeb.WS.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(AllLifePricingWeb.WS.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AllLifePricingWeb.WS.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(AllLifePricingWeb.WS.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnPremium", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnPremiumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string coverValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        public returnPremiumRequest() {
        }
        
        public returnPremiumRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.coverValue = coverValue;
            this.quoteDate = quoteDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnPremiumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnPremiumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnPremiumResult;
        
        public returnPremiumResponse() {
        }
        
        public returnPremiumResponse(System.Data.DataTable returnPremiumResult) {
            this.returnPremiumResult = returnPremiumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnRisk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnRiskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string coverValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string premiumValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inceptionDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string effectiveDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string durationModifierCode;
        
        public returnRiskRequest() {
        }
        
        public returnRiskRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.coverValue = coverValue;
            this.premiumValue = premiumValue;
            this.quoteDate = quoteDate;
            this.inceptionDate = inceptionDate;
            this.effectiveDate = effectiveDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
            this.durationModifierCode = durationModifierCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnRiskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnRiskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnRiskResult;
        
        public returnRiskResponse() {
        }
        
        public returnRiskResponse(System.Data.DataTable returnRiskResult) {
            this.returnRiskResult = returnRiskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnCover", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnCoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string premiumValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        public returnCoverRequest() {
        }
        
        public returnCoverRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.premiumValue = premiumValue;
            this.quoteDate = quoteDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnCoverResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnCoverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnCoverResult;
        
        public returnCoverResponse() {
        }
        
        public returnCoverResponse(System.Data.DataTable returnCoverResult) {
            this.returnCoverResult = returnCoverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_Premium", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_PremiumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string coverValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMloading;
        
        public returnEM_Affected_PremiumRequest() {
        }
        
        public returnEM_Affected_PremiumRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.coverValue = coverValue;
            this.quoteDate = quoteDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
            this.EMloading = EMloading;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_PremiumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_PremiumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnEM_Affected_PremiumResult;
        
        public returnEM_Affected_PremiumResponse() {
        }
        
        public returnEM_Affected_PremiumResponse(System.Data.DataTable returnEM_Affected_PremiumResult) {
            this.returnEM_Affected_PremiumResult = returnEM_Affected_PremiumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_Risk", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_RiskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string coverValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string premiumValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string inceptionDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string effectiveDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string durationModifierCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMloading;
        
        public returnEM_Affected_RiskRequest() {
        }
        
        public returnEM_Affected_RiskRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode, string EMloading) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.coverValue = coverValue;
            this.premiumValue = premiumValue;
            this.quoteDate = quoteDate;
            this.inceptionDate = inceptionDate;
            this.effectiveDate = effectiveDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
            this.durationModifierCode = durationModifierCode;
            this.EMloading = EMloading;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_RiskResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_RiskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnEM_Affected_RiskResult;
        
        public returnEM_Affected_RiskResponse() {
        }
        
        public returnEM_Affected_RiskResponse(System.Data.DataTable returnEM_Affected_RiskResult) {
            this.returnEM_Affected_RiskResult = returnEM_Affected_RiskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_Cover", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_CoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string baseRisk;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string premiumValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string customerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quotationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMloading;
        
        public returnEM_Affected_CoverRequest() {
        }
        
        public returnEM_Affected_CoverRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.baseRisk = baseRisk;
            this.riskModifier = riskModifier;
            this.premiumValue = premiumValue;
            this.quoteDate = quoteDate;
            this.customerID = customerID;
            this.quotationID = quotationID;
            this.EMloading = EMloading;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnEM_Affected_CoverResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnEM_Affected_CoverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnEM_Affected_CoverResult;
        
        public returnEM_Affected_CoverResponse() {
        }
        
        public returnEM_Affected_CoverResponse(System.Data.DataTable returnEM_Affected_CoverResult) {
            this.returnEM_Affected_CoverResult = returnEM_Affected_CoverResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnRiskBand", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnRiskBandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string riskModifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string quoteDate;
        
        public returnRiskBandRequest() {
        }
        
        public returnRiskBandRequest(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string riskModifier, string quoteDate) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.productCode = productCode;
            this.riskModifier = riskModifier;
            this.quoteDate = quoteDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnRiskBandResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class returnRiskBandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable returnRiskBandResult;
        
        public returnRiskBandResponse() {
        }
        
        public returnRiskBandResponse(System.Data.DataTable returnRiskBandResult) {
            this.returnRiskBandResult = returnRiskBandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QualifyLife", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QualifyLifeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgeNextBirthday;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TobaccoUse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HbA1cPercent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BMI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PantSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlcoholUnitsPerDay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Occupation;
        
        public QualifyLifeRequest() {
        }
        
        public QualifyLifeRequest(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Occupation) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.AgeNextBirthday = AgeNextBirthday;
            this.TobaccoUse = TobaccoUse;
            this.HbA1cPercent = HbA1cPercent;
            this.BMI = BMI;
            this.PantSize = PantSize;
            this.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            this.Occupation = Occupation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QualifyLifeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QualifyLifeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable QualifyLifeResult;
        
        public QualifyLifeResponse() {
        }
        
        public QualifyLifeResponse(System.Data.DataTable QualifyLifeResult) {
            this.QualifyLifeResult = QualifyLifeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QualifyDisability", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QualifyDisabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string subscriberCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AgeNextBirthday;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TobaccoUse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HbA1cPercent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BMI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PantSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlcoholUnitsPerDay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Employment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Qualification;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Income;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SpouseIncome;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RiskBand;
        
        public QualifyDisabilityRequest() {
        }
        
        public QualifyDisabilityRequest(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Employment, string Qualification, string Income, string SpouseIncome, string RiskBand) {
            this.subscriberName = subscriberName;
            this.subscriberPassword = subscriberPassword;
            this.subscriberCode = subscriberCode;
            this.AgeNextBirthday = AgeNextBirthday;
            this.TobaccoUse = TobaccoUse;
            this.HbA1cPercent = HbA1cPercent;
            this.BMI = BMI;
            this.PantSize = PantSize;
            this.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            this.Employment = Employment;
            this.Qualification = Qualification;
            this.Income = Income;
            this.SpouseIncome = SpouseIncome;
            this.RiskBand = RiskBand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QualifyDisabilityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QualifyDisabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable QualifyDisabilityResult;
        
        public QualifyDisabilityResponse() {
        }
        
        public QualifyDisabilityResponse(System.Data.DataTable QualifyDisabilityResult) {
            this.QualifyDisabilityResult = QualifyDisabilityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllLifePrincingChannel : AllLifePricingWeb.WS.IAllLifePrincing, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllLifePrincingClient : System.ServiceModel.ClientBase<AllLifePricingWeb.WS.IAllLifePrincing>, AllLifePricingWeb.WS.IAllLifePrincing {
        
        public AllLifePrincingClient() {
        }
        
        public AllLifePrincingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllLifePrincingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllLifePrincingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllLifePrincingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.GetDataResponse AllLifePricingWeb.WS.IAllLifePrincing.GetData(AllLifePricingWeb.WS.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(string value) {
            AllLifePricingWeb.WS.GetDataRequest inValue = new AllLifePricingWeb.WS.GetDataRequest();
            inValue.value = value;
            AllLifePricingWeb.WS.GetDataResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).GetData(inValue);
            return retVal.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataResponse> AllLifePricingWeb.WS.IAllLifePrincing.GetDataAsync(AllLifePricingWeb.WS.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataResponse> GetDataAsync(string value) {
            AllLifePricingWeb.WS.GetDataRequest inValue = new AllLifePricingWeb.WS.GetDataRequest();
            inValue.value = value;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.GetDataUsingDataContractResponse AllLifePricingWeb.WS.IAllLifePrincing.GetDataUsingDataContract(AllLifePricingWeb.WS.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public AllLifePricingWeb.WS.CompositeType GetDataUsingDataContract(AllLifePricingWeb.WS.CompositeType composite) {
            AllLifePricingWeb.WS.GetDataUsingDataContractRequest inValue = new AllLifePricingWeb.WS.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            AllLifePricingWeb.WS.GetDataUsingDataContractResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).GetDataUsingDataContract(inValue);
            return retVal.GetDataUsingDataContractResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataUsingDataContractResponse> AllLifePricingWeb.WS.IAllLifePrincing.GetDataUsingDataContractAsync(AllLifePricingWeb.WS.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(AllLifePricingWeb.WS.CompositeType composite) {
            AllLifePricingWeb.WS.GetDataUsingDataContractRequest inValue = new AllLifePricingWeb.WS.GetDataUsingDataContractRequest();
            inValue.composite = composite;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).GetDataUsingDataContractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnPremiumResponse AllLifePricingWeb.WS.IAllLifePrincing.returnPremium(AllLifePricingWeb.WS.returnPremiumRequest request) {
            return base.Channel.returnPremium(request);
        }
        
        public System.Data.DataTable returnPremium(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID) {
            AllLifePricingWeb.WS.returnPremiumRequest inValue = new AllLifePricingWeb.WS.returnPremiumRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            AllLifePricingWeb.WS.returnPremiumResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnPremium(inValue);
            return retVal.returnPremiumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnPremiumResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnPremiumAsync(AllLifePricingWeb.WS.returnPremiumRequest request) {
            return base.Channel.returnPremiumAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnPremiumResponse> returnPremiumAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID) {
            AllLifePricingWeb.WS.returnPremiumRequest inValue = new AllLifePricingWeb.WS.returnPremiumRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnPremiumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnRiskResponse AllLifePricingWeb.WS.IAllLifePrincing.returnRisk(AllLifePricingWeb.WS.returnRiskRequest request) {
            return base.Channel.returnRisk(request);
        }
        
        public System.Data.DataTable returnRisk(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode) {
            AllLifePricingWeb.WS.returnRiskRequest inValue = new AllLifePricingWeb.WS.returnRiskRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.inceptionDate = inceptionDate;
            inValue.effectiveDate = effectiveDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.durationModifierCode = durationModifierCode;
            AllLifePricingWeb.WS.returnRiskResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnRisk(inValue);
            return retVal.returnRiskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnRiskAsync(AllLifePricingWeb.WS.returnRiskRequest request) {
            return base.Channel.returnRiskAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskResponse> returnRiskAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode) {
            AllLifePricingWeb.WS.returnRiskRequest inValue = new AllLifePricingWeb.WS.returnRiskRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.inceptionDate = inceptionDate;
            inValue.effectiveDate = effectiveDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.durationModifierCode = durationModifierCode;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnRiskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnCoverResponse AllLifePricingWeb.WS.IAllLifePrincing.returnCover(AllLifePricingWeb.WS.returnCoverRequest request) {
            return base.Channel.returnCover(request);
        }
        
        public System.Data.DataTable returnCover(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID) {
            AllLifePricingWeb.WS.returnCoverRequest inValue = new AllLifePricingWeb.WS.returnCoverRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            AllLifePricingWeb.WS.returnCoverResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnCover(inValue);
            return retVal.returnCoverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnCoverResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnCoverAsync(AllLifePricingWeb.WS.returnCoverRequest request) {
            return base.Channel.returnCoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnCoverResponse> returnCoverAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID) {
            AllLifePricingWeb.WS.returnCoverRequest inValue = new AllLifePricingWeb.WS.returnCoverRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnCoverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_Premium(AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest request) {
            return base.Channel.returnEM_Affected_Premium(request);
        }
        
        public System.Data.DataTable returnEM_Affected_Premium(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.EMloading = EMloading;
            AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_Premium(inValue);
            return retVal.returnEM_Affected_PremiumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_PremiumAsync(AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest request) {
            return base.Channel.returnEM_Affected_PremiumAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_PremiumResponse> returnEM_Affected_PremiumAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_PremiumRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.EMloading = EMloading;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_PremiumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnEM_Affected_RiskResponse AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_Risk(AllLifePricingWeb.WS.returnEM_Affected_RiskRequest request) {
            return base.Channel.returnEM_Affected_Risk(request);
        }
        
        public System.Data.DataTable returnEM_Affected_Risk(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_RiskRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_RiskRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.inceptionDate = inceptionDate;
            inValue.effectiveDate = effectiveDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.durationModifierCode = durationModifierCode;
            inValue.EMloading = EMloading;
            AllLifePricingWeb.WS.returnEM_Affected_RiskResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_Risk(inValue);
            return retVal.returnEM_Affected_RiskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_RiskResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_RiskAsync(AllLifePricingWeb.WS.returnEM_Affected_RiskRequest request) {
            return base.Channel.returnEM_Affected_RiskAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_RiskResponse> returnEM_Affected_RiskAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string coverValue, string premiumValue, string quoteDate, string inceptionDate, string effectiveDate, string customerID, string quotationID, string durationModifierCode, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_RiskRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_RiskRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.coverValue = coverValue;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.inceptionDate = inceptionDate;
            inValue.effectiveDate = effectiveDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.durationModifierCode = durationModifierCode;
            inValue.EMloading = EMloading;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_RiskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnEM_Affected_CoverResponse AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_Cover(AllLifePricingWeb.WS.returnEM_Affected_CoverRequest request) {
            return base.Channel.returnEM_Affected_Cover(request);
        }
        
        public System.Data.DataTable returnEM_Affected_Cover(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_CoverRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_CoverRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.EMloading = EMloading;
            AllLifePricingWeb.WS.returnEM_Affected_CoverResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_Cover(inValue);
            return retVal.returnEM_Affected_CoverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_CoverResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnEM_Affected_CoverAsync(AllLifePricingWeb.WS.returnEM_Affected_CoverRequest request) {
            return base.Channel.returnEM_Affected_CoverAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnEM_Affected_CoverResponse> returnEM_Affected_CoverAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string baseRisk, string riskModifier, string premiumValue, string quoteDate, string customerID, string quotationID, string EMloading) {
            AllLifePricingWeb.WS.returnEM_Affected_CoverRequest inValue = new AllLifePricingWeb.WS.returnEM_Affected_CoverRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.baseRisk = baseRisk;
            inValue.riskModifier = riskModifier;
            inValue.premiumValue = premiumValue;
            inValue.quoteDate = quoteDate;
            inValue.customerID = customerID;
            inValue.quotationID = quotationID;
            inValue.EMloading = EMloading;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnEM_Affected_CoverAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.returnRiskBandResponse AllLifePricingWeb.WS.IAllLifePrincing.returnRiskBand(AllLifePricingWeb.WS.returnRiskBandRequest request) {
            return base.Channel.returnRiskBand(request);
        }
        
        public System.Data.DataTable returnRiskBand(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string riskModifier, string quoteDate) {
            AllLifePricingWeb.WS.returnRiskBandRequest inValue = new AllLifePricingWeb.WS.returnRiskBandRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.riskModifier = riskModifier;
            inValue.quoteDate = quoteDate;
            AllLifePricingWeb.WS.returnRiskBandResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnRiskBand(inValue);
            return retVal.returnRiskBandResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskBandResponse> AllLifePricingWeb.WS.IAllLifePrincing.returnRiskBandAsync(AllLifePricingWeb.WS.returnRiskBandRequest request) {
            return base.Channel.returnRiskBandAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.returnRiskBandResponse> returnRiskBandAsync(string subscriberName, string subscriberPassword, string subscriberCode, string productCode, string riskModifier, string quoteDate) {
            AllLifePricingWeb.WS.returnRiskBandRequest inValue = new AllLifePricingWeb.WS.returnRiskBandRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.productCode = productCode;
            inValue.riskModifier = riskModifier;
            inValue.quoteDate = quoteDate;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).returnRiskBandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.QualifyLifeResponse AllLifePricingWeb.WS.IAllLifePrincing.QualifyLife(AllLifePricingWeb.WS.QualifyLifeRequest request) {
            return base.Channel.QualifyLife(request);
        }
        
        public System.Data.DataTable QualifyLife(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Occupation) {
            AllLifePricingWeb.WS.QualifyLifeRequest inValue = new AllLifePricingWeb.WS.QualifyLifeRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.AgeNextBirthday = AgeNextBirthday;
            inValue.TobaccoUse = TobaccoUse;
            inValue.HbA1cPercent = HbA1cPercent;
            inValue.BMI = BMI;
            inValue.PantSize = PantSize;
            inValue.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            inValue.Occupation = Occupation;
            AllLifePricingWeb.WS.QualifyLifeResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).QualifyLife(inValue);
            return retVal.QualifyLifeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyLifeResponse> AllLifePricingWeb.WS.IAllLifePrincing.QualifyLifeAsync(AllLifePricingWeb.WS.QualifyLifeRequest request) {
            return base.Channel.QualifyLifeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyLifeResponse> QualifyLifeAsync(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Occupation) {
            AllLifePricingWeb.WS.QualifyLifeRequest inValue = new AllLifePricingWeb.WS.QualifyLifeRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.AgeNextBirthday = AgeNextBirthday;
            inValue.TobaccoUse = TobaccoUse;
            inValue.HbA1cPercent = HbA1cPercent;
            inValue.BMI = BMI;
            inValue.PantSize = PantSize;
            inValue.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            inValue.Occupation = Occupation;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).QualifyLifeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AllLifePricingWeb.WS.QualifyDisabilityResponse AllLifePricingWeb.WS.IAllLifePrincing.QualifyDisability(AllLifePricingWeb.WS.QualifyDisabilityRequest request) {
            return base.Channel.QualifyDisability(request);
        }
        
        public System.Data.DataTable QualifyDisability(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Employment, string Qualification, string Income, string SpouseIncome, string RiskBand) {
            AllLifePricingWeb.WS.QualifyDisabilityRequest inValue = new AllLifePricingWeb.WS.QualifyDisabilityRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.AgeNextBirthday = AgeNextBirthday;
            inValue.TobaccoUse = TobaccoUse;
            inValue.HbA1cPercent = HbA1cPercent;
            inValue.BMI = BMI;
            inValue.PantSize = PantSize;
            inValue.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            inValue.Employment = Employment;
            inValue.Qualification = Qualification;
            inValue.Income = Income;
            inValue.SpouseIncome = SpouseIncome;
            inValue.RiskBand = RiskBand;
            AllLifePricingWeb.WS.QualifyDisabilityResponse retVal = ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).QualifyDisability(inValue);
            return retVal.QualifyDisabilityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyDisabilityResponse> AllLifePricingWeb.WS.IAllLifePrincing.QualifyDisabilityAsync(AllLifePricingWeb.WS.QualifyDisabilityRequest request) {
            return base.Channel.QualifyDisabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<AllLifePricingWeb.WS.QualifyDisabilityResponse> QualifyDisabilityAsync(string subscriberName, string subscriberPassword, string subscriberCode, string AgeNextBirthday, string TobaccoUse, string HbA1cPercent, string BMI, string PantSize, string AlcoholUnitsPerDay, string Employment, string Qualification, string Income, string SpouseIncome, string RiskBand) {
            AllLifePricingWeb.WS.QualifyDisabilityRequest inValue = new AllLifePricingWeb.WS.QualifyDisabilityRequest();
            inValue.subscriberName = subscriberName;
            inValue.subscriberPassword = subscriberPassword;
            inValue.subscriberCode = subscriberCode;
            inValue.AgeNextBirthday = AgeNextBirthday;
            inValue.TobaccoUse = TobaccoUse;
            inValue.HbA1cPercent = HbA1cPercent;
            inValue.BMI = BMI;
            inValue.PantSize = PantSize;
            inValue.AlcoholUnitsPerDay = AlcoholUnitsPerDay;
            inValue.Employment = Employment;
            inValue.Qualification = Qualification;
            inValue.Income = Income;
            inValue.SpouseIncome = SpouseIncome;
            inValue.RiskBand = RiskBand;
            return ((AllLifePricingWeb.WS.IAllLifePrincing)(this)).QualifyDisabilityAsync(inValue);
        }
    }
}
